# action name 설정
name: Deploy-main-push
# push를 통해서 trigger하는 방법
# if (branches == stage) && (path == serviceA 이하 변경) => trigger action
#
on:
  push:
    branches:
      - stage
    paths:
      - 'serviceA/**'
# jobs을 정의
jobs:
  # job 정의
  print-tag:
    # 작업을 실행할 시스템 정의
    runs-on: ubuntu-latest
    # 프로세스 정의
    steps:
      # 프로세스-1 (example)
      - name: echo~
        run: echo I'm going to build Dockerfile in serviceA